【WIP】パスワード変更画面の作成
saito-kazumasa/equipment-management-system pull request #103
Opened 2024-07-12 03:45 UTC by AirikU

## 概要

close #25 

- パスワード変更画面(headerが空の状態)

### スクリーンショット

- パスワード変更画面
![スクリーンショット 2024-07-12 124049](https://github.com/user-attachments/assets/455feaa2-9ec0-4752-82be-269fe5d33fd4)

### チェックリスト

- [ ] エラーが出ていない
- [ ] 動作確認を行い、正常に動作した

2024-07-17 02:23 UTC, AirikU commented
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/cce0dfb528324e2ba03e9da44a19f0d3cdc9552b
  - 画面でheaderが表示されるかを確認するために、ここでは認可を.permitAll()に設定
  - 本来は、.authenticated()にする箇所

2024-07-17 03:22 UTC, AirikU commented
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/a2a0b5f6b791d225b4671b0953f8bf8633971296
  - 本来は、ログインしているユーザーのメールアドレスが表示される形式

2024-07-17 04:43 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +    }
確か前にパスワード変更画面は成功/失敗画面を作成せずに
![image](https://github.com/user-attachments/assets/61f969e3-746e-4a03-9a58-4a61a7334b45)
こんな感じでアカウント詳細画面に戻って結果を表示するように変わったはず

2024-07-17 05:09 UTC, AirikU commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +    }
その処理は「パスワードを忘れた画面」だけだと思っていたので、作成していました。

2024-07-17 06:07 UTC, AirikU commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +    }
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/a5ec02b7c6fd32937d27701a66674e2d9bf8976a
リダイレクトで戻るように修正しました。

2024-07-17 06:20 UTC, AirikU commented
このプルリク内で、本来動作する処理に修正したほうが良いですか？
- リクエストの認可の設定　https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/d6203b0eefbc5f3da3d9413bbc3a372a746fd5bc
- メールアドレスの表示　https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/a2a0b5f6b791d225b4671b0953f8bf8633971296
- リダイレクトで戻る画面　https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/a5ec02b7c6fd32937d27701a66674e2d9bf8976a

2024-07-17 06:42 UTC, saito-kazumasa requested changes
何だか今まで僕が送ってきたPRを見ていなかったり、話を聞いていないのだなと感じ、残念に思いました。
きちんとPRを見てください。話を聞いてください。

2024-07-17 06:42 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
> +                        .requestMatchers("/password_change").permitAll()
ここはログインしていなければ入れないはずです。
permitAll()にしないでください。

2024-07-17 06:42 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +    }
早期リターン推奨です。
また、Model や RedirectAttributes に送る際、("message", message) ではなく、(message) だけにする、という話を前していたと思います。

```suggestion
    @PostMapping()
    public String post(final RedirectAttributes redirectAttributes) {
        final boolean result = true;

        if (result) {
            final var message = new SuccessMessage("送信しました。");
            redirectAttributes.addFlashAttribute(message);
            return "redirect:遷移先"
        } 
        
        final var message = new ErrorMessage("送信時にエラーが発生しました。");
        redirectAttributes.addFlashAttribute(message);
        return "redirect:/password_change";
    }
```

2024-07-17 06:42 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +@RequestMapping("/password_change")
パスワード変更画面は、マイアカウントの画面から連なってくるものです。
また、permitAll()でアクセスできる所ではないので、/直下にルーティングしないでください。

2024-07-17 06:42 UTC, saito-kazumasa commented on src/main/resources/templates/password_change.html
> +    <p class="text-gray text-center text-3xl my-10">abc@sample.ac.jp</p>
なぜ値直書きなのでしょうか。
th:text は付けないのですか？

2024-07-17 06:42 UTC, saito-kazumasa commented on src/main/resources/templates/password_change.html
> +            <a th:href="@{/login}" class="text-primary underline">キャンセル</a>
ログイン画面に遷移するんですか？

2024-07-17 06:42 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +        final boolean result = true;
これは true にしかなりませんが、良いんですか？

2024-07-17 06:46 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +    }
@AirikU 川口君が言ってること、もう一回良く読んでみて。

2024-07-19 03:17 UTC, AirikU commented on src/main/resources/templates/password_change.html
> +            <a th:href="@{/login}" class="text-primary underline">キャンセル</a>
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/94e128b938609086e52c782a89fea138bf3f3f25
遷移先画面名を指定しました。

2024-07-19 03:18 UTC, AirikU commented on src/main/resources/templates/password_change.html
> +    <p class="text-gray text-center text-3xl my-10">abc@sample.ac.jp</p>
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/a2e186e3bbb8aa6c58dc5b749ef4b5f2f51ab208
th:textで、データベースからの値を表示するようにしました。

メールアドレスが画面でどのように表示されるのかを確認するために、書いていたものです。

2024-07-19 03:29 UTC, AirikU commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +@RequestMapping("/password_change")
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/73cf929f344bb3b8e002952de4eaade59ecc5fbd
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/eec6b1ecc44c7b3f5615e99ab21f3e4bdcf1cd8b
  - パスをファイルの格納位置に適したものに変更しました。

2024-07-19 05:46 UTC, AirikU commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +        final boolean result = true;
PasswordResetController.javaを基に作成したのですが、resultの値を切り替える方法が分かりませんでした。

2024-07-19 06:00 UTC, AirikU commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordChangeController.java
> +    }
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/550064675ca9ee6b94f88948f306b9b295ff6da3
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/6db8e3158dfbfbef299467bb873e7efff50a1828
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/e3ab02ff0571b7e1b712de17d74ab9fe3f6db390
  - メッセージの表示を、早期リターンの形に変更しました。
  - 遷移先の画面がない箇所は、遷移先の画面名を明記しました。
  - (message)に変更して、メッセージが表示されなくなりました。

[PasswordResetContoller.java](https://github.com/saito-kazumasa/equipment-management-system/blob/main/src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordResetController.java)に、("message", message)と(message)があるのですが、このブランチ以外で修正しますか？

2024-07-19 06:05 UTC, AirikU commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
> +                        .requestMatchers("/password_change").permitAll()
- https://github.com/saito-kazumasa/equipment-management-system/pull/103/commits/3dcfe184a6298a022f3a1c768515e43545980e5b
リクエストの認可を「.authenticated()」に変更しました。

2024-08-22 00:26 UTC, closed without merging