Feature/return application
saito-kazumasa/equipment-management-system pull request #106
Opened 2024-07-17 04:10 UTC by ken-250

## 概要

close #38 

- 備品の返却申請機能を作成
- 備品の異常申請機能を作成

### スクリーンショット

![return_application](https://github.com/user-attachments/assets/7e6906e5-98e0-4bb0-9bbf-f9ef52592952)

### チェックリスト

- [x] エラーが出ていない
- [x] 動作確認を行い、正常に動作した

2024-07-17 06:52 UTC, saito-kazumasa commented
まずはコンフリクトの解消をお願いします :pray:

2024-07-18 03:10 UTC, ken-250 reviewed
service / controllerのパッケージ名で `return` が使用できなかったため `toReturn` という名前で作成。

2024-07-18 03:32 UTC, AirikU approved these changes
レビュー完了しました。

2024-07-19 03:31 UTC, saito-kazumasa requested changes
一旦ここまでレビュー

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/form/ReturnApplicationForm.java
> +    private final String mail;
mail は取らずに、controller の引数として @AuthenticationPrincipal ? かなんかで取りましょう。

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/form/ReturnApplicationForm.java
> +
json という名前では情報がなさすぎるため、名前を変更しましょう。
（ちなみに、checkoutApplicationForm では json にしか関心がないクラスのため許されます。）

また、できるなら別々のクラスにしたいです。
ここは要検討。

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
> +                        .requestMatchers("/return/**").authenticated()
```suggestion
                        .requestMatchers("/return/**").permitAll()
```

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/toReturn/ReturnApplicationController.java
> +    }
```suggestion
    public String get(final Model model,
                      final @AuthenticationPrincipal UserDetails userDetails) {
        final String mail= userDetails.getUsername();
        final ReturnApplicationForm returnApplicationForm = ReturnApplicationForm.empty();
        // 借りている備品を取得（返却承認されていないもののみ） ←コメントで補足しなくてもわかる関数名を付けましょう。
        final List<Equipment> equipmentList = equipmentsService.executeLending(mail);
        
        model.addAttribute(mail);
        model.addAttribute(returnApplicationForm );
        model.addAttribute(equipmentList);

        return "return/application/application";
    }
```

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/toReturn/ReturnApplicationController.java
> +        final int damageApplicationResult = damageApplicationService.execute(returnApplicationForm);
備品に破損がない時もこのサービスを通るのは変な感じがします。
返却と破損、どちらもを処理するサービスを作り、その中で返却と破損のサービスを受け取り、処理させる形だと自然かなと思います。

→ ... 依存の方向
RetrunApplicationController → 返却と破損どちらも一緒に処理するサービス
返却と破損どちらも一緒に処理するサービス → IReturnApplicationService, IDamageApplicationService

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICheckoutApplicationsMapper.java
> +    public CheckoutApplication selectNotReturned(final int accountId, final int equipmentId);
ca ca2 はなしです。

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentsMapper.java
> +    public List<Equipment> selectLending(final int accountId);
ca ca2 はなしです

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/checkout/implement/ApplyCheckoutService.java
> +    }
変数名、クラス名を考えてみてください。

ApplyCheckoutService.execute() → 貸出申請(サービス).実行()
ApplyCheckoutService.executeNotReturned() → 貸出申請(サービス).返却していないものに実行

しかし、この関数では select しかしていないように見えます。

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/damage/implement/ApplyDamageService.java
> +    public ApplyDamageService(IDamagedApplicationsMapper damagedApplicationMapper, IAccountsMapper accountsMapper, ICheckoutApplicationsMapper checkoutApplicationsMapper) {
```suggestion
    public ApplyDamageService(
        final IDamagedApplicationsMapper damagedApplicationMapper,
        final IAccountsMapper accountsMapper,
        final ICheckoutApplicationsMapper checkoutApplicationsMapper
    ) {
```

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/damage/implement/ApplyDamageService.java
> +        return 1;
早期リターン推奨です。
送信するアカウントは、返却する備品から貸出申請を参照し、アカウントIDを持ってくればいけそう。

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/equipment/IFetchEquipmentService.java
> +    public List<Equipment> executeAll();
これは ListEquipmentService にすでにあります

2024-07-19 03:31 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/equipment/IFetchEquipmentService.java
> +    public List<Equipment> executeLending(final String mail);
複数とるときは ListEquipmentService に書きます

2024-07-19 04:26 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
> +                        .requestMatchers("/return/**").authenticated()
permitAll()に変更
[8889c7f](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/8889c7fe3988c8c4cce1f4520ebaeefe378ee11c)

2024-07-19 04:27 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/form/ReturnApplicationForm.java
> +    private final String mail;
formでmailを使用しないように変更
[22c8c03](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/22c8c03af86cfc885be4618f0d568993a5baa4c1)

2024-07-19 04:54 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/toReturn/ReturnApplicationController.java
> +    }
修正しました
[8ae14c0](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/8ae14c0ab0166be6a5e37a7f2f57cd5fef2825d1)

2024-07-19 05:05 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentsMapper.java
> +    public List<Equipment> selectLending(final int accountId);
変更しました
[a5bd094](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/a5bd094d0d5f729b2955034f91f2b9607ad65f10)

2024-07-19 05:05 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICheckoutApplicationsMapper.java
> +    public CheckoutApplication selectNotReturned(final int accountId, final int equipmentId);
変更しました
[a5bd094](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/a5bd094d0d5f729b2955034f91f2b9607ad65f10)

2024-07-19 05:08 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/damage/implement/ApplyDamageService.java
> +    public ApplyDamageService(IDamagedApplicationsMapper damagedApplicationMapper, IAccountsMapper accountsMapper, ICheckoutApplicationsMapper checkoutApplicationsMapper) {
直しました
[3d5157c](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/3d5157cd1b597e3a29bd448dc86fd3c2ff84102f)

2024-07-19 05:44 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/damage/implement/ApplyDamageService.java
> +        return 1;
修正しました。
[9e8b25c](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/9e8b25c5abb4824fa28100cf94c62a8860ce977a)

2024-07-19 05:49 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/form/ReturnApplicationForm.java
> +
変更しました（クラス分けは未着手）
[ed04346](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/ed043461b6df2625d6855082c8349befa36f381a)

2024-07-19 06:03 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/checkout/implement/ApplyCheckoutService.java
> +    }
fetch*****に変更しました
[6f64495](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/6f64495c6237fb9de221befddfadc48c012c8340)

2024-07-19 06:06 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/equipment/IFetchEquipmentService.java
> +    public List<Equipment> executeAll();
削除しました
[3a16ded](https://github.com/saito-kazumasa/equipment-management-system/pull/106/commits/3a16ded91cd45127f8de2b837b7dc2c460927c93)

2024-08-21 05:44 UTC, saito-kazumasa commented
僕が修正するため、一旦すべて解決にしました

2024-08-21 13:53 UTC, saito-kazumasa approved these changes
修正完了

2024-08-21 15:29 UTC, merged