[Feature]ログインページの作成
saito-kazumasa/equipment-management-system pull request #59
Opened 2024-06-11 03:36 UTC by AirikU

## 概要

close #20

- ログインページと入力フォームを作成(htmlファイルのみ)

### スクリーンショット

![スクリーンショット 2024-06-11 123059](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/62295b2f-6269-4c51-959a-b7fe28729e9d)

## チェックリスト
- [ ] エラーが出ていないか

2024-06-11 03:41 UTC, AirikU commented
現時点では、画像ファイルの中に画像(カメラのアイコン)を置いています。
cssは、bootstrapなしで作成出来たらと考えています。

2024-06-11 03:42 UTC, saito-kazumasa requested changes
issue を close するならCSSまでお願いします。
close せずに一旦 html だけマージして欲しい、ということであれば close を消してください。

2024-06-11 03:44 UTC, ken-250 requested changes
上に同じく

2024-06-11 03:48 UTC, ken-250 requested changes

2024-06-11 03:48 UTC, ken-250 commented on src/main/resources/templates/login/login_top.html
> +        <div class="alert alert-danger p-2"></div>
bootstrapを使わないのであれば class="alert" などは使用できないはず。

2024-06-11 03:48 UTC, ken-250 commented on src/main/resources/templates/login/login_top.html
> +        <div class="alert alert-danger p-2"></div>
bootstrapを使わないのであれば class="alert" などは使用できないはず。

2024-06-11 03:49 UTC, saito-kazumasa requested changes
今の時点でのレビューを付けました。
確認よろしくお願いします。

2024-06-11 03:49 UTC, saito-kazumasa commented on src/main/resources/templates/images/camera.png
images フォルダは resources/templates ではなく、resources/static にお願いします。

2024-06-11 03:49 UTC, saito-kazumasa commented on src/main/resources/templates/login/login_top.html
> +<html lang="en">
lang は 日本語表示しかしないため、"ja" にしてください。

2024-06-11 03:49 UTC, saito-kazumasa commented on src/main/resources/templates/login/login_top.html
> +    <title>login_top</title>
title はなぜ英語なのでしょうか

2024-06-11 03:49 UTC, saito-kazumasa commented on src/main/resources/templates/login/login_top.html
> +    <a href="#">パスワードを忘れた方はこちら</a>
ヘッダーには `<header>` が付いているから、個人的にはメインコンテンツは `<main>` を付けたいです。
@ken-250 どう思う？

2024-06-11 03:49 UTC, saito-kazumasa commented on src/main/resources/templates/images/camera.png
ちなみにこの画像はどこからとってきましたか？
なんか画質 粗い気がします。

2024-06-12 03:43 UTC, AirikU commented on src/main/resources/templates/images/camera.png
ファイル移動しました。

2024-06-12 03:44 UTC, AirikU commented on src/main/resources/templates/login/login_top.html
> +<html lang="en">
コードを変更しました。

2024-06-12 03:46 UTC, AirikU commented on src/main/resources/templates/login/login_top.html
> +    <title>login_top</title>
これまでのSpringの授業では、編集しなかった関係でタイトルが英語だったので、英語の方が良いと思っていました。
その部分を日本語に変更しました。

2024-06-12 03:46 UTC, AirikU commented on src/main/resources/templates/login/login_top.html
> +    <a href="#">パスワードを忘れた方はこちら</a>
コード修正しました。

2024-06-12 03:47 UTC, AirikU commented on src/main/resources/templates/images/camera.png
画像の元サイズを大きいサイズに変更しました。

2024-06-12 03:49 UTC, AirikU commented on src/main/resources/templates/login/login_top.html
> +        <div class="alert alert-danger p-2"></div>
コードを削除しました。
bootstrapを使用せずにエラーメッセージを表示する方法はありますか。

2024-06-12 04:45 UTC, AirikU commented on src/main/resources/templates/login/login_top.html
> +        <div class="alert alert-danger p-2"></div>
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/c914a969dd05a41bffb518b28b5b9e0aedcba339

2024-06-12 04:46 UTC, AirikU commented on src/main/resources/templates/login/login_top.html
> +<html lang="en">
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/5de996052609de4ba4e90c3488c90fd484c90353

2024-06-12 04:47 UTC, AirikU commented on src/main/resources/templates/login/login_top.html
> +    <a href="#">パスワードを忘れた方はこちら</a>
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/918a1427dc759685a28a5dfb64a19309f0affadc

2024-06-12 04:47 UTC, AirikU commented on src/main/resources/templates/images/camera.png
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/51913748f98b433cacc6f059d3b4886893d319eb

2024-06-12 04:48 UTC, AirikU commented on src/main/resources/templates/images/camera.png
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/f59763e9f2fb85c244dfe8b591464c97298aa7b8

2024-06-12 04:49 UTC, AirikU commented on src/main/resources/templates/login/login_top.html
> +    <title>login_top</title>
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/c82c01e36a7c84f2100bf9168a900c915b4bceef

2024-06-12 04:50 UTC, saito-kazumasa commented on src/main/resources/templates/images/camera.png
実行してみましたか？
多分だけど、この相対リンクだと動かないのでは。（動いたらごめん）

以下で行けると思います。
`<img src="/images/camera.png" alt="顔認証のボタン">`

2024-06-12 04:51 UTC, saito-kazumasa commented on src/main/resources/templates/login/login_top.html
> +<html lang="en">
ありがとう 😘

2024-06-12 04:51 UTC, ken-250 commented on src/main/resources/templates/login/login_top.html
> +        <div class="alert alert-danger p-2"></div>
bootstrapはあくまでデザインを付けるためだけに使用するのでメッセージ自体はSpringBootのthymeleafを利用して表示します。
デザインを付けたい場合は、普通にCSSで付ければ解決すると思います。

2024-06-12 04:53 UTC, saito-kazumasa commented on src/main/resources/templates/login/login_top.html
> +    <title>login_top</title>
以下の場合は、基本的にどの部分も日本語で表示するのが良いと思います。

- 日本人向けのサイトである
- 英語圏の人が利用する予定がない or ほぼない

何故かわからない場合は教えてください。

2024-06-12 04:54 UTC, saito-kazumasa commented on src/main/resources/templates/login/login_top.html
> +    <a href="#">パスワードを忘れた方はこちら</a>
ありがとう 😍

2024-06-12 04:56 UTC, saito-kazumasa commented on src/main/resources/templates/images/camera.png
画像サイズ、あまり変わってないっぽいですよ
![image](https://github.com/saito-kazumasa/equipment-management-system/assets/95904285/0b6ea037-b2fc-4819-b6b5-41e94b15299c)

2024-06-14 03:22 UTC, AirikU commented on src/main/resources/templates/images/camera.png
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/f8ce07346699e0c47a3a22e1ee86fe15db5b785a
画像のサイズを変更しました。
ページ全体のバランスはどうですか？
![スクリーンショット 2024-06-14 121852](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/86a99a37-d30a-4f22-ab01-bc46215f7ac8)

2024-06-14 03:48 UTC, AirikU commented
![スクリーンショット 2024-06-14 124801](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/6c490089-28ef-473b-b44c-374a04fc1826)

2024-06-14 06:24 UTC, saito-kazumasa commented on src/main/resources/templates/images/camera.png
`128px × 128px` か `256px × 256px` にしてください、と指定したと思います。
ページ全体のバランスについては、Figmaの通り画像のサイズを修正してください。

2024-06-17 01:50 UTC, AirikU commented on src/main/resources/templates/images/camera.png
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/0dbf588864c9a88a450a463e99a29036cfc6a399

2024-06-17 02:08 UTC, saito-kazumasa commented on src/main/resources/templates/images/camera.png
画像をお願いします。

2024-06-17 02:13 UTC, saito-kazumasa commented
コミットメッセージが気になったため共有です。
`[fix]` は バグ修正、`[feature]` は機能の作成っぽく感じます。
指摘の修正、更新や変更は `[update]`、何かの追加（機能追加ほど大きくはない）は `[add]` かなと感じます。

2024-06-17 02:14 UTC, AirikU commented on src/main/resources/templates/images/camera.png
![スクリーンショット 2024-06-17 111233](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/73bc7012-5c65-4148-b963-a0d6d46c3142)

2024-06-17 02:21 UTC, saito-kazumasa commented on src/main/resources/templates/images/camera.png
ありがとう 😘

2024-06-17 02:37 UTC, AirikU commented on src/main/resources/templates/images/camera.png
相対リンクの件で、htmlファイルから直接Chromeを開くと、画像が表示されるのですが、EquipmentManagementSystemApplicationから実行しようとすると、エラーが出て実行できない状態なので、直接Chromeを開く方法でcssデザインをしていました。
この方法だと、相対リンクで書かないと、画像が表示されませんでした

![スクリーンショット 2024-06-17 112534](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/dde4a87a-723a-4bc7-b075-81a8362853e4)
![スクリーンショット 2024-06-17 113227](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/381f6519-6f05-4b86-a849-8786df9fa62e)

![スクリーンショット 2024-06-17 113606](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/3da1d303-b33a-4e5f-ad1e-36e8bfe8081b)
![スクリーンショット 2024-06-17 113630](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/b09bb2d0-d03f-456c-ab9c-60f9973dc559)

2024-06-17 02:38 UTC, AirikU commented on src/main/resources/templates/images/camera.png
※EquipmentManagementSystemApplicationで実行できなかった際のエラーメッセージ
![スクリーンショット 2024-06-17 113120](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/4551e198-c188-472c-bcb1-b113f7ca0696)

2024-06-17 03:05 UTC, AirikU commented on src/main/resources/templates/images/camera.png
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/1a150dc4f6db641b59745d1621495dbb9af3f1c5

EquipmentManagementSystemApplicationからの実行が出来るようになりました。

2024-06-17 07:46 UTC, AirikU commented on src/main/resources/templates/images/camera.png
パスの再変更
https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/a59360d68c3b7680377407c05b2d02ff4297b52b

2024-06-17 07:48 UTC, AirikU commented on src/main/resources/templates/login/login_top.html
> +        <div class="alert alert-danger p-2"></div>
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/a59360d68c3b7680377407c05b2d02ff4297b52b
cssとpタグでメッセージを追加しました。

2024-06-18 02:41 UTC, AirikU commented
ページ間で共通しているデザインを、login_top.cssからsite_common.cssに移動させました。
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/323d9c221dc84be84ce4aaa040b5513d8e88f450
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/1b0aba0fbef2ec0bff8a2fc047665ce7045e4c51

2024-06-18 03:38 UTC, AirikU commented
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/ac58f12630c0d97348b1d10649ad96a7b242a4de
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/328d446948f2d3924b417b2cc4f8c403d8261846
- https://github.com/saito-kazumasa/equipment-management-system/pull/59/commits/19551bb72b97a9d21c23648a446d261cdcb6672b

Figmaのデザインを元にしたログインページが出来ました。
![スクリーンショット 2024-06-18 123651](https://github.com/saito-kazumasa/equipment-management-system/assets/101164630/4245ba86-427c-4409-a487-13cfbaeb7c02)

2024-06-18 03:47 UTC, saito-kazumasa commented
申し訳ないのですが、ここまでの作業を見て完成の見込みが立たないため、Tailwindを使う方針に変更します。

2024-06-18 03:47 UTC, closed without merging