保管場所DBの Mapper&Entiry を作成した
saito-kazumasa/equipment-management-system pull request #71
Opened 2024-06-12 05:57 UTC by ken-250

## 概要

close #8 

- entityを作成した
- mapperを作成した

### スクリーンショット
特になし

### チェックリスト

- [x] エラーが出ていない
- [ ] ~~動作確認を行い、正常に動作した~~

2024-06-12 06:01 UTC, saito-kazumasa requested changes
確認お願いします。

2024-06-12 06:01 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/EquipmentCategory.java
> +}
多分コミットするブランチを間違えてる？

2024-06-12 06:01 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentCategoryMapper.java
> +
何も書いてないっす！！！

2024-06-12 06:01 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IStorageLocationMapper.java
> +
何も書いてないっす！！

2024-06-12 06:06 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/EquipmentCategory.java
> +}
多分間違ってEquipmentCategoryMapperのブランチから切ってる

2024-06-12 06:10 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentCategoryMapper.java
> +
insert文追加しました
[9ba318e](https://github.com/saito-kazumasa/equipment-management-system/pull/71/commits/9ba318e295dce586e5b6395e7036e43e9a8e0965)

2024-06-12 06:10 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IStorageLocationMapper.java
> +
insert文追加しました
[9ba318e](https://github.com/saito-kazumasa/equipment-management-system/pull/71/commits/9ba318e295dce586e5b6395e7036e43e9a8e0965)

2024-06-12 06:13 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/EquipmentCategory.java
> +}
そうしたら、EquipmentCategoryMapperのブランチがマージされてからレビューします

2024-06-14 06:19 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IStorageLocationMapper.java
> +
`final` 警察通ります。
引数に `final` を付けてください。

2024-06-17 01:04 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IStorageLocationMapper.java
> +
[c750535](https://github.com/saito-kazumasa/equipment-management-system/pull/71/commits/c75053577a688ece0c52ddfbe46ac38e8e5dabb6)

2024-06-17 02:25 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IStorageLocationMapper.java
> +
ありがとう 😘

2024-06-17 02:25 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentCategoryMapper.java
> +
別ブランチの変更でした。
解決。

2024-06-17 02:25 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/EquipmentCategory.java
> +}
別ブランチの変更でした。
解決。

2024-06-17 02:26 UTC, saito-kazumasa approved these changes
LGTM

2024-06-17 02:39 UTC, AirikU approved these changes
レビュー完了しました。

2024-06-17 02:39 UTC, merged