ページ作成に使用するアイコンを追加
saito-kazumasa/equipment-management-system pull request #80
Opened 2024-06-19 06:42 UTC by AirikU

## 概要

- サイズ→256px
- Figmaでデザインされているものを基に、これまでに追加されていなかったアイコンを追加しました。
- デザイン上では、アイコンを使っていないところ(メニュー{MenuIcon.png})も、アイコンから追加してみました。
  ※コメントで、どの画面で使用するか可能性があるのかを、補足します。
- その他追加・削除の要望があれば、コメント等お願いします。

### スクリーンショット

なし(変更内容を参照)

### チェックリスト

- [ ] 今回追加したアイコンで、全てのページ作成が可能かどうか

2024-06-19 06:44 UTC, AirikU commented on src/main/resources/static/images/BarcordIcon.png
- 備品詳細画面

2024-06-19 06:54 UTC, AirikU commented on src/main/resources/static/images/BlueCheckIcon.png
チェック(青)
- 返却申請画面(紛失/破損の事由を入力するポップアップフォーム)
- 備品一覧-検索画面
- 備品編集画面
- 備品登録画面
- 返却申請-承認画面(紛失/破損の事由を入力するポップアップフォーム)　※リンクから飛ぶ画面

2024-06-19 06:59 UTC, AirikU commented on src/main/resources/static/images/GlassIcon.png
検索
- 備品一覧系画面(備品一覧-検索・備品登録-送信成功＆送信失敗を含む)
- アカウント一覧画面

2024-06-19 07:01 UTC, AirikU commented on src/main/resources/static/images/GrayCheckIcon.png
チェック(黒)
- 備品編集-確認画面
- 備品登録-確認画面

2024-06-19 07:08 UTC, AirikU commented on src/main/resources/static/images/MenuIcon.png
メニュー
- ログインする前の画面(ログイン・パスワードを忘れた・カメラ起動時)
- メニュー画面(メニューを開いたとき)
- リンクから飛ぶ画面(各種申請承認{ポップアップ画面を含む}・承認成功・承認失敗、パスワード変更・送信成功・送信失敗)

**上記以外全ての画面**

2024-06-19 07:11 UTC, AirikU commented on src/main/resources/static/images/WhiteCheckIcon.png
チェック(白)
- 各種成功画面のメッセージ部分(備品編集-送信成功・備品登録-送信成功・アカウント編集-送信成功・顔認証登録-成功)

2024-06-19 07:35 UTC, saito-kazumasa commented
このチェックリストは、PRを出す人自身がチェックする項目です。
書き換えないでください。また自分でPRを出す前にチェックしてください。

![image](https://github.com/saito-kazumasa/equipment-management-system/assets/95904285/a3988c27-a991-4012-b22c-ea4c07ac4df6)

2024-06-19 07:45 UTC, saito-kazumasa commented
このように複数コメントに渡って書かれると非常に見づらいです。
コメントで補足せず、概要にきちんとまとめて書いてください。
※ただし、後から補足したくて、レビュワーに通知させたい場合は別

![image](https://github.com/saito-kazumasa/equipment-management-system/assets/95904285/976f2baf-4b5f-4c46-9254-6e13ae4db776)

----
  
例)
## 概要
追加したアイコンリスト
- src/main/resources/static/images/BarcordIcon.png ... バーコードアイコン

（というかどの画面で使うかの情報はぶっちゃけ見りゃ分かるので要らない、もっと他の時間を使うべき所に使ってくれ）

2024-06-19 07:49 UTC, saito-kazumasa requested changes
いくつかコメントしました。

2024-06-19 07:49 UTC, saito-kazumasa commented on src/main/resources/static/images/BarcordIcon.png
なるべく白の画像で欲しいです。

2024-06-19 07:49 UTC, saito-kazumasa commented on src/main/resources/static/images/BlueCheckIcon.png
こちらも同じく白でお願いします。
あと、ファイル名に "blue" と入れるのは良くないです。
何故良くないのか、わからなかったら聞いてください。

2024-06-19 07:49 UTC, saito-kazumasa commented on src/main/resources/static/images/GrayCheckIcon.png
白のチェックアイコン入れて、CSSとかで色変更して使えばファイル一つで済むのでは。

2024-06-19 07:49 UTC, saito-kazumasa commented on src/main/resources/static/images/MenuIcon.png
これはアイコンでやらないため不要です。

2024-06-21 02:37 UTC, AirikU commented
- https://github.com/saito-kazumasa/equipment-management-system/pull/80/commits/3240c56af98468bf01a671cf3751dcde06df4ea2
  - メニューアイコンの削除
  - チェックアイコンを1つに
- https://github.com/saito-kazumasa/equipment-management-system/pull/80/commits/a7c93fb3ba3fe11fa29ae1ac8577d9a462accc92
  - 色を白に変更
- https://github.com/saito-kazumasa/equipment-management-system/pull/80/commits/47788e52c615e6335b296dfcaee7b03ba75957af
  - 1つにしたチェックアイコンのファイル名を変更

2024-06-21 03:51 UTC, saito-kazumasa commented
修正コメントは各コメントに対して、1つずつ返信してください。

2024-06-24 02:16 UTC, AirikU commented on src/main/resources/static/images/MenuIcon.png
- https://github.com/saito-kazumasa/equipment-management-system/commit/3240c56af98468bf01a671cf3751dcde06df4ea2
  - メニューアイコンの削除

2024-06-24 02:17 UTC, AirikU commented on src/main/resources/static/images/BarcordIcon.png
- https://github.com/saito-kazumasa/equipment-management-system/commit/a7c93fb3ba3fe11fa29ae1ac8577d9a462accc92
  - 色を白に変更

2024-06-24 02:19 UTC, AirikU commented on src/main/resources/static/images/BlueCheckIcon.png
- https://github.com/saito-kazumasa/equipment-management-system/commit/3240c56af98468bf01a671cf3751dcde06df4ea2
  - チェックアイコンを1つに
- https://github.com/saito-kazumasa/equipment-management-system/commit/47788e52c615e6335b296dfcaee7b03ba75957af
  - 1つにしたチェックアイコンのファイル名を変更

2024-06-24 02:19 UTC, AirikU commented on src/main/resources/static/images/GrayCheckIcon.png
- https://github.com/saito-kazumasa/equipment-management-system/commit/3240c56af98468bf01a671cf3751dcde06df4ea2
  - チェックアイコンを1つに
- https://github.com/saito-kazumasa/equipment-management-system/commit/47788e52c615e6335b296dfcaee7b03ba75957af
  - 1つにしたチェックアイコンのファイル名を変更

2024-06-24 02:51 UTC, saito-kazumasa commented on src/main/resources/static/images/BarcordIcon.png
ありがとうございます

2024-06-24 02:52 UTC, saito-kazumasa commented on src/main/resources/static/images/BlueCheckIcon.png
ありがとうございます
ただ、一つのコミットで複数の修正をしないようにしてください。

2024-06-24 02:52 UTC, saito-kazumasa commented on src/main/resources/static/images/GrayCheckIcon.png
こちらも同様。

2024-06-24 02:53 UTC, saito-kazumasa commented on src/main/resources/static/images/MenuIcon.png
一つのコミットで複数の修正をしないでください。

2024-06-26 05:12 UTC, AirikU commented
プルリクのチェックリストを元の項目に戻しました。
レビューする人にチェックしてもらう項目だと思っていました。
追加したのがプログラムコードではなかったので、エラーとは関係ないと思い書き換えてしまいました。

2024-06-26 05:24 UTC, AirikU commented
最終的にこのプルリクで追加したアイコンリスト

- src/main/resources/static/images/barcord-icon.png　バーコードアイコン(バーコード再発行)
- src/main/resources/static/images/check-icon.png　チェックアイコン(チェックボックス)
- src/main/resources/static/images/glass-icon.png　虫眼鏡アイコン(検索)
- src/main/resources/static/images/xlsxfile-icon.png　Excelファイルアイコン(ファイルを開く)

2024-06-28 04:44 UTC, saito-kazumasa approved these changes
LGTM

2024-06-28 04:45 UTC, ken-250 approved these changes
確認しました。

2024-06-28 04:45 UTC, merged