貸出申請機能を作成
saito-kazumasa/equipment-management-system pull request #86
Opened 2024-06-24 04:46 UTC by ken-250

## 概要

close #39

- 貸出申請画面で備品IDを入力し対象の備品情報を取得して表示する
- 備品の貸出申請を行う

### スクリーンショット

![image](https://github.com/saito-kazumasa/equipment-management-system/assets/101164631/f9276164-711b-496b-b15f-92d32895f2ed)

### チェックリスト

- [x] エラーが出ていない
- [x] 動作確認を行い、正常に動作した

2024-06-24 06:10 UTC, saito-kazumasa requested changes
とりあえずここまでのコードをレビューしました。

2024-06-24 06:10 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +    let equipmentIds = [];
頭に _ を付けたいです。
_ + 変数名

2024-06-24 06:10 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +    });
早期リターン推奨です。
※早期リターンの影響を考慮してないため、いい感じに修正してください。

```suggestion
    document.getElementById('equipment-info').addEventListener('click', (e) => {
        if (e.target.tagName !== 'BUTTON') return;
        
         // リストから対象の備品を削除
         const equipmentId = e.target.parentElement.id;
         equipmentIds = equipmentIds.filter(id => id !== equipmentId);
         equipmentIdsElement.value = equipmentIds;
         e.target.parentElement.remove();
        
        // メッセージを更新
        if (equipmentIds.length === 0) messageElement.innerText = "備品を選択してください。";
        else  messageElement.innerText = "";
    });
```

2024-06-24 06:10 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +                messageElement.innerText = "備品情報を取得できませんでした。";
早期リターン推奨です。

2024-06-24 06:10 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +                equipmentIdsElement.value = equipmentIds;
コメント及び、順番等々の整理お願いします。

2024-06-26 02:35 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public CheckoutController(EquipmentsService equipmentsService, CheckoutApplicationsService checkoutApplicationsService) {
`final` 追加しました。
[a71d99f](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/a71d99ff6d36e5363fcb5617b4e6a83861d7be8b)

2024-06-26 02:35 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public String application(Model model) {
`final` 追加しました。
[a71d99f](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/a71d99ff6d36e5363fcb5617b4e6a83861d7be8b)

2024-06-26 02:36 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public String application(@RequestParam String[] equipmentIds, RedirectAttributes redirectAttributes) {
`final` 追加しました。
[a71d99f](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/a71d99ff6d36e5363fcb5617b4e6a83861d7be8b)

2024-06-26 02:36 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public Equipment addList(@RequestParam int equipmentId) {
`final` 追加しました。
[a71d99f](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/a71d99ff6d36e5363fcb5617b4e6a83861d7be8b)

2024-06-26 02:42 UTC, ken-250 commented on src/main/resources/templates/checkout/application.html
> +    let equipmentIds = [];
修正しました。
[ed6b014](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/ed6b014eda62432f26c866f4647dd283a544d395)

2024-06-26 02:53 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/CheckoutApplicationsService.java
> +public interface CheckoutApplicationsService {
アノテーションを削除しました。
[6d2477e](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/6d2477ee5bec52900da641e5841d15ae3331b34a)

名前はまだ変更していません。

2024-06-26 02:53 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/EquipmentsService.java
> +@Service
アノテーションを削除しました。
[6d2477e](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/6d2477ee5bec52900da641e5841d15ae3331b34a)

2024-06-26 02:58 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/CheckoutApplicationsService.java
> +    public void insert(CheckoutApplication checkoutApplication);
`final` を追加しました。
[a5dd382](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/a5dd382411f947f1ff79bab8a86e3539c38dc234)

2024-06-26 02:58 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/EquipmentsService.java
> +    void insert(Equipment equipment);
`final` を追加しました。
[a5dd382](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/a5dd382411f947f1ff79bab8a86e3539c38dc234)

2024-06-26 02:58 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/EquipmentsService.java
> +    Equipment selectById(int id);
`final` を追加しました。
[a5dd382](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/a5dd382411f947f1ff79bab8a86e3539c38dc234)

2024-06-26 03:03 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/CheckoutApplicationsImpl.java
> +    public CheckoutApplicationsImpl(ICheckoutApplicationsMapper checkoutApplicationsMapper) {
`final` 追加しました。
[1ace2e1](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/1ace2e1ed4b642e7c1b37191ab0ee9d25b98fad1)

2024-06-26 03:03 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/CheckoutApplicationsImpl.java
> +    public void insert(CheckoutApplication checkoutApplication) {
`final` 追加しました。
[1ace2e1](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/1ace2e1ed4b642e7c1b37191ab0ee9d25b98fad1)

2024-06-26 03:04 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/EquipmentsImpl.java
> +    }
`final` 追加しました。
[1ace2e1](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/1ace2e1ed4b642e7c1b37191ab0ee9d25b98fad1)

2024-06-26 03:59 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/CheckoutApplicationsImpl.java
> +public class CheckoutApplicationsImpl implements CheckoutApplicationsService{
implを削除しました。
[08e722b](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/08e722b49a5272ccba4550e69e287c23d397bb78)

2024-06-26 03:59 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/EquipmentsImpl.java
> +public class EquipmentsImpl implements EquipmentsService {
implを削除しました。
[08e722b](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/08e722b49a5272ccba4550e69e287c23d397bb78)

2024-06-26 04:29 UTC, ken-250 commented on src/main/resources/templates/checkout/application.html
> +</div>
コメント修正しました。
[8b231d6](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/8b231d6ed7c5cd0d3642d954a7ee1b1a9bfb07ef)

2024-06-26 04:34 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEditLogsMapper.java
> +//}
コメントアウトを解除しました。
[252c978](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/252c9785becee5c4d73a51b7db41465980daa522)

2024-06-26 04:35 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public CheckoutController(EquipmentsService equipmentsService, CheckoutApplicationsService checkoutApplicationsService) {
ありがとうございます 😘

2024-06-26 04:35 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public String application(@RequestParam String[] equipmentIds, RedirectAttributes redirectAttributes) {
ありがとうございます 😘

2024-06-26 04:36 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public Equipment addList(@RequestParam int equipmentId) {
ありがとうございます 😘

2024-06-26 04:41 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/CheckoutApplicationsService.java
> +public interface CheckoutApplicationsService {
インターフェースの変数名は I なしで 小文字初め でお願いします。

2024-06-26 04:41 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/CheckoutApplicationsService.java
> +    public void insert(CheckoutApplication checkoutApplication);
ありがとうございます 😘

2024-06-26 04:43 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/EquipmentsService.java
> +    Equipment selectById(int id);
インターフェースの変数名は I なし キャメルケース でお願いします。

2024-06-26 04:44 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/CheckoutApplicationsImpl.java
> +public class CheckoutApplicationsImpl implements CheckoutApplicationsService{
関数名に Service をお願いします。

2024-06-26 04:45 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/CheckoutApplicationsImpl.java
> +    public void insert(CheckoutApplication checkoutApplication) {
ありがとうございます 😘

2024-06-26 04:45 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/EquipmentsImpl.java
> +    }
ありがとうございます 😘

2024-06-26 04:46 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +    let equipmentIds = [];
ありがとうございます 😘

2024-06-26 04:46 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEditLogsMapper.java
> +//}
ありがとうございます 😘

2024-06-26 04:46 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public String application(Model model) {
ありがとうございます 😘

2024-06-26 04:47 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/CheckoutApplicationsImpl.java
> +    public CheckoutApplicationsImpl(ICheckoutApplicationsMapper checkoutApplicationsMapper) {
ありがとうございます 😘

2024-06-26 04:48 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/EquipmentsImpl.java
> +public class EquipmentsImpl implements EquipmentsService {
関数名に Service を付けてほしいです。

2024-06-26 04:48 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +</div>
ありがとうございます 😘

2024-06-26 05:00 UTC, ken-250 commented on src/main/resources/templates/checkout/application.html
> +<script>
別ファイルに記述するように変更しました。
[04c2caa](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/04c2caa09971519b1ed955e4863be44b68a474b8)

2024-06-26 05:03 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/EquipmentsService.java
> +    Equipment selectById(int id);
変数名を修正しました。
[f7c6d84](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/f7c6d84a281c8b1346d6860f80aea7b592fabf17)

2024-06-26 05:08 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/CheckoutApplicationsService.java
> +public interface CheckoutApplicationsService {
変数名を修正しました。
[48c71a2](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/48c71a20d0b68901483c281b3d64eabe2263c3db)

2024-06-26 05:09 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/CheckoutApplicationsService.java
> +public interface CheckoutApplicationsService {
ありがとうございます

2024-06-26 05:09 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/EquipmentsService.java
> +    Equipment selectById(int id);
ありがとうございます

2024-06-26 05:10 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/CheckoutApplicationsImpl.java
> +public class CheckoutApplicationsImpl implements CheckoutApplicationsService{
付けました。
[92063c7](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/92063c7788c23765e7fb0f788d7cb5b13e17470e)

2024-06-26 05:11 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/EquipmentsImpl.java
> +public class EquipmentsImpl implements EquipmentsService {
付けました。
[4476387](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/447638754f846f23ebe8d8715d2274875cde5c9a)

2024-06-26 05:12 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/CheckoutApplicationsImpl.java
> +public class CheckoutApplicationsImpl implements CheckoutApplicationsService{
ありがとうございます

2024-06-26 05:12 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/EquipmentsImpl.java
> +public class EquipmentsImpl implements EquipmentsService {
ありがとうございます

2024-06-26 05:12 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +<script>
ありがとうございます

2024-07-02 03:29 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +                equipmentIdsElement.value = equipmentIds;
JSは一緒に編集したため解決とします。

2024-07-02 03:29 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +                messageElement.innerText = "備品情報を取得できませんでした。";
JSは一緒に編集したため解決とします。

2024-07-02 03:29 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +    });
JSは一緒に編集したため解決とします。

2024-07-02 03:29 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +    // ✕ボタンをクリックしたときの処理
JSは一緒に編集したため解決とします。

2024-07-02 03:30 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +    });
JSは一緒に編集したため解決とします。

2024-07-02 03:30 UTC, saito-kazumasa commented on src/main/resources/templates/checkout/application.html
> +    // ＋ボタンをクリックしたときの処理
JSは一緒に編集したため解決とします。

2024-07-03 02:15 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/CheckoutApplicationsService.java
> +    public void insert(CheckoutApplication checkoutApplication);
修正しました。
[833217f](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/833217f4e83731c49352967026aeac3997817341)

controller側も修正。
[6796538](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/67965388d2f06b271cc81a4710ef5334873171db)

2024-07-03 02:20 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/CheckoutApplicationsService.java
> +    public void insert(CheckoutApplication checkoutApplication);
一旦最新のものをレビューしなおすため、解決にします。

2024-07-03 02:30 UTC, saito-kazumasa requested changes
最新の状態でのレビューを追加しました。

2024-07-03 02:30 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public String application(Model model) {
`final` がなくなっている！！？

2024-07-03 02:30 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    }
要編集

2024-07-03 02:30 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentsMapper.java
> +    @Select("SELECT * FROM equipments")
order by をお願いします。

2024-07-03 02:30 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/ICheckoutApplicationsService.java
> +    public void checkoutExec(final CheckoutApplication checkoutApplication);
名前は省略しないでください。

2024-07-03 02:30 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/IEquipmentsService.java
> +    List<Equipment> getAll();
これは共通認識として持っておいて欲しいのですが、
get() は単純な値の取得のみ、重い処理も全くない関数、として考えてほしいです。

今回の場合は、個人的にDBに接続する関係上 get() と付けられるほどの軽さには感じないです。

2024-07-03 02:30 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/ICheckoutApplicationsService.java
> +    public void checkoutExec(final CheckoutApplication checkoutApplication);
それと、checkoutExecute() だと、冗長な名前だと思います。
普通に execute() だけで良いのでは。

2024-07-03 02:32 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    public String application(Model model) {
付けました
[f650d3a](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/f650d3a983125cb45dda2bdc241bd5b3c3799ca3)

2024-07-03 02:34 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/ICheckoutApplicationsService.java
> +    public void checkoutExec(final CheckoutApplication checkoutApplication);
修正しました。
[98cfa81](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/98cfa8176bc9beb163d30c3c2fb2fe7a2775b900)

2024-07-03 02:42 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentsMapper.java
> +    @Select("SELECT * FROM equipments")
IDの昇順で取得するように修正しました。
[132b488](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/132b488b850d29b57b2fa3b98b0e526bce11a10f)

2024-07-03 03:03 UTC, ken-250 commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/IEquipmentsService.java
> +    List<Equipment> getAll();
外部から取得するという意味で `fetch〇〇` に変更しました。
[2264ceb](https://github.com/saito-kazumasa/equipment-management-system/pull/86/commits/2264ceb94cf55ba4df63c23d6905d4953bc8b9ed)

2024-07-04 02:35 UTC, saito-kazumasa commented on src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutController.java
> +    }
完了

2024-07-04 02:39 UTC, saito-kazumasa approved these changes
LGTM, お疲れ様です。

2024-07-04 03:00 UTC, AirikU approved these changes
レビュー完了しました。

2024-07-04 03:00 UTC, merged